# Generated by Django 2.2.12 on 2020-06-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UvaSolve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('url_txt', models.URLField(max_length=100)),
                ('description', models.TextField()),
                ('critical_input', models.TextField()),
                ('critical_output', models.TextField()),
                ('code_txt', models.TextField()),
            ],
        ),
    ]
